version: '3.8'

services:
  # postgres:
  #   image: postgres:15-alpine
  #   container_name: newsradar_postgres
  #   environment:
  #     POSTGRES_USER: newsradar_user
  #     POSTGRES_PASSWORD: newsradar_password
  #     POSTGRES_DB: newsradar_db
  #   ports:
  #     - "5432:5432" # Mapeamos el puerto para que FastAPI pueda acceder desde fuera del contenedor
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   restart: unless-stopped

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: newsradar_elastic
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false # Desactivamos seguridad temporalmente para facilitar desarrollo local
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" # Limitamos la RAM para que no nos congele el ordenador
    ports:
      - "9200:9200"
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    restart: unless-stopped

volumes:
  postgres_data:
  elastic_data: